version: '2'
services:
  redis-cluster:
    build:
      context: .
    hostname: server
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7002:7002"
      - "7003:7003"
      - "7004:7004"
      - "7005:7005"
